//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelcoBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelcoBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new users.
        /// </summary>
        internal static string AddingNewUsersProcessLabel {
            get {
                return ResourceManager.GetString("AddingNewUsersProcessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That bill has already been paid..
        /// </summary>
        internal static string BillAlreadyPaidMessage {
            get {
                return ResourceManager.GetString("BillAlreadyPaidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string BillingLabel {
            get {
                return ResourceManager.GetString("BillingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversation has been reset. You will have to verify your identify again..
        /// </summary>
        internal static string ConversationReset {
            get {
                return ResourceManager.GetString("ConversationReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string CurrentLabel {
            get {
                return ResourceManager.GetString("CurrentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Service.
        /// </summary>
        internal static string CurrentServiceHeader {
            get {
                return ResourceManager.GetString("CurrentServiceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, pay {0}.
        /// </summary>
        internal static string FinalPaymentConfirmationLabel {
            get {
                return ResourceManager.GetString("FinalPaymentConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of your {0} {1} bill is {2}. Do you want to charge your {3} for that amount?.
        /// </summary>
        internal static string FinalPaymentConfirmationPromptTemplate {
            get {
                return ResourceManager.GetString("FinalPaymentConfirmationPromptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        internal static string GoBackLabel {
            get {
                return ResourceManager.GetString("GoBackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I don&apos;t understand that..
        /// </summary>
        internal static string IncomprehensionMessage {
            get {
                return ResourceManager.GetString("IncomprehensionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not the PIN I have for you..
        /// </summary>
        internal static string IncorrectPinMessage {
            get {
                return ResourceManager.GetString("IncorrectPinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string InternetLabel {
            get {
                return ResourceManager.GetString("InternetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}/mo..
        /// </summary>
        internal static string InternetServiceTitleTemplate {
            get {
                return ResourceManager.GetString("InternetServiceTitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Full Invoice.
        /// </summary>
        internal static string InvoiceDetailLabel {
            get {
                return ResourceManager.GetString("InvoiceDetailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing invoice detail.
        /// </summary>
        internal static string InvoiceDetailProcessLabel {
            get {
                return ResourceManager.GetString("InvoiceDetailProcessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        internal static string InvoiceSubtitleTemplate {
            get {
                return ResourceManager.GetString("InvoiceSubtitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        internal static string LastMonthToken {
            get {
                return ResourceManager.GetString("LastMonthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item from the menu, or just type what you want to do..
        /// </summary>
        internal static string MainMenuDirections {
            get {
                return ResourceManager.GetString("MainMenuDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great. Let me pull up the main menu..
        /// </summary>
        internal static string MainMenuMessage {
            get {
                return ResourceManager.GetString("MainMenuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, it&apos;s different.
        /// </summary>
        internal static string MatchNoLabel {
            get {
                return ResourceManager.GetString("MatchNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, that&apos;s it.
        /// </summary>
        internal static string MatchYesLabel {
            get {
                return ResourceManager.GetString("MatchYesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string MonthEntityType {
            get {
                return ResourceManager.GetString("MonthEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is &quot;{0} {1}&quot; the name associated with your {2} account?.
        /// </summary>
        internal static string NameAssociationPromptTemplate {
            get {
                return ResourceManager.GetString("NameAssociationPromptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t recognize that name..
        /// </summary>
        internal static string NameNotFoundMessage {
            get {
                return ResourceManager.GetString("NameNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevermind.
        /// </summary>
        internal static string NevermindLabel {
            get {
                return ResourceManager.GetString("NevermindLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a new user.
        /// </summary>
        internal static string NewUserLabel {
            get {
                return ResourceManager.GetString("NewUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t see any billing history in your records..
        /// </summary>
        internal static string NoBillingRecordsMessage {
            get {
                return ResourceManager.GetString("NoBillingRecordsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t see an unpaid bill matching &quot;{0}&quot;.
        /// </summary>
        internal static string NoMatchingUnpaidBillMessageTemplate {
            get {
                return ResourceManager.GetString("NoMatchingUnpaidBillMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t see any payment methods in your records..
        /// </summary>
        internal static string NoPaymentMethodsMessage {
            get {
                return ResourceManager.GetString("NoPaymentMethodsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoServiceLabel {
            get {
                return ResourceManager.GetString("NoServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not {0} {1}.
        /// </summary>
        internal static string NotMeLabelTemplate {
            get {
                return ResourceManager.GetString("NotMeLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} are not yet supported..
        /// </summary>
        internal static string NotSupportedTemplatePlural {
            get {
                return ResourceManager.GetString("NotSupportedTemplatePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not yet supported..
        /// </summary>
        internal static string NotSupportedTemplateSingular {
            get {
                return ResourceManager.GetString("NotSupportedTemplateSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string PaidLabel {
            get {
                return ResourceManager.GetString("PaidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAST DUE.
        /// </summary>
        internal static string PastDueLabel {
            get {
                return ResourceManager.GetString("PastDueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentMethod.
        /// </summary>
        internal static string PaymentMethodEntityType {
            get {
                return ResourceManager.GetString("PaymentMethodEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to pay today?.
        /// </summary>
        internal static string PaymentMethodPrompt {
            get {
                return ResourceManager.GetString("PaymentMethodPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Now.
        /// </summary>
        internal static string PayNowLabel {
            get {
                return ResourceManager.GetString("PayNowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay {0} Bill.
        /// </summary>
        internal static string PayThisBillLabelTemplate {
            get {
                return ResourceManager.GetString("PayThisBillLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To verify your identity, please send me your Personal Identification Number (PIN).
        /// </summary>
        internal static string PinPrompt {
            get {
                return ResourceManager.GetString("PinPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service inquiries.
        /// </summary>
        internal static string ServiceInquiriesLabel {
            get {
                return ResourceManager.GetString("ServiceInquiriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check my Service.
        /// </summary>
        internal static string ServiceInquiryLabel {
            get {
                return ResourceManager.GetString("ServiceInquiryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been charged {0}. Thank you for your payment!.
        /// </summary>
        internal static string ThanksForPaymentMessageTemplate {
            get {
                return ResourceManager.GetString("ThanksForPaymentMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This.
        /// </summary>
        internal static string ThisMonthToken {
            get {
                return ResourceManager.GetString("ThisMonthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string TvLabel {
            get {
                return ResourceManager.GetString("TvLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV service upgrades.
        /// </summary>
        internal static string TvServiceLabel {
            get {
                return ResourceManager.GetString("TvServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you have upgraded to {0}!.
        /// </summary>
        internal static string UpgradeConfirmationTemplate {
            get {
                return ResourceManager.GetString("UpgradeConfirmationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrades.
        /// </summary>
        internal static string UpgradeLabel {
            get {
                return ResourceManager.GetString("UpgradeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Now!.
        /// </summary>
        internal static string UpgradeNowLabel {
            get {
                return ResourceManager.GetString("UpgradeNowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To upgrade, lease click on the upgrade button of your preferred plan..
        /// </summary>
        internal static string UpgradePrompt {
            get {
                return ResourceManager.GetString("UpgradePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By what name do I know you?.
        /// </summary>
        internal static string WhatNamePrompt {
            get {
                return ResourceManager.GetString("WhatNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which service would you like to upgrade?.
        /// </summary>
        internal static string WhichServiceQuestion {
            get {
                return ResourceManager.GetString("WhichServiceQuestion", resourceCulture);
            }
        }
    }
}
